### ISSUE TITLE
NoSuchMethodError Issue

### ISSUE THREAD

**Issue by AyMarte** [Jozufozu/Flywheel#209]
### Describe the Bug

When I've countlessly opened this mod with the Create mod, 
_version-specific details below_, I'd have gotten the same error over and over again.
```
java.lang.NoSuchMethodError: 'com.tterrag.registrate.util.nullness.NonNullSupplier com.simibubi.create.foundation.data.CreateRegistrate.lazy(java.lang.String)'
```

### Reproduction Steps

1. Loading Up The Version In Any Of The Versions Of Create From The Latest  To The First Version Supported With 1.19.2 and with an "E" along with this mod.

### Expected Result

The Minecraft Menu Screen To Pop-up

### Screenshots and Videos

![ErrorLog](https://github.com/Jozufozu/Flywheel/assets/112666885/d328fe7f-3aca-485b-9f5a-b468d528932c)

### Crash Report or Log

[Latest.log](https://pastebin.com/VHWMn6SU)

### Operating System

Windows 11

### What is your GPU?

Not sure but is similar with the Intel Core i5.

### Mod Version

0.6.10

### Minecraft Version

1.20.1

### Loader Version

Forge 43.3.0

### Other Mods

Create Confectionery - _Not the main cause_,
Pehkui & Fabric API - _Found out was not the issue either_,
Immersive Portals - _Also found out not to be the main cause_.

**Comment by PepperCode1** [comment]
This is not the Extended Flywheel repository. Flywheel is a rendering library that Create uses, not a Create addon.
